### PR TITLE
Wairarapa and S. Hawkes Baysins

### PR DESCRIPTION
**Pull request by jasonmotha**
Wairarapa:
[CrossSection_vs_slices.pdf](https://github.com/ucgmsim/Velocity-Model/files/7681574/CrossSection_vs_slices.pdf)
[VelModDomainBox.pdf](https://github.com/ucgmsim/Velocity-Model/files/7681576/VelModDomainBox.pdf)
SHB:
[CrossSection_vs_slices.pdf](https://github.com/ucgmsim/Velocity-Model/files/7681615/CrossSection_vs_slices.pdf)
[VelModDomainBox.pdf](https://github.com/ucgmsim/Velocity-Model/files/7681616/VelModDomainBox.pdf)

### CODE REVIEW

**Comment by AndrewStolte** [comment]
The correct outlines are missing on the map PDF files.

**Comment by jasonmotha** [comment]
I'm not sure how those outlines work. It seems like they are there for any pre-USER basin but aren't there for any newer basin. That outline is for the original Wellington Basin.

**Comment by lee-robin** [comment]
Files and file changes look good. Would have liked the outlines on the domain box pdfs but it sounds like the functionality is actually a mystery? Alternatively you could pass me the cross section coordinates and I can quickly draw it up in Python to put the slices into perspective.

As a side note I also checked the SHB boundary doesn't overlap with the Napier/Hawkes Bay basin. It looks good, William did very well with it.

**Comment by jasonmotha** [comment]
[SliceParametersAuto.txt](https://github.com/ucgmsim/Velocity-Model/files/7681862/SliceParametersAuto.txt)
[SliceParametersAuto.txt](https://github.com/ucgmsim/Velocity-Model/files/7681864/SliceParametersAuto.txt)
Here's the two slice parameter files.
@lee-robin

**Comment by AndrewStolte** [comment]
I think it looks okay => good to go. Looking at Robin's python generated maps does help provide context (i.e., those already on the basin modeling slack).

Maybe worth figuring out how to add the new outlines to the domain box pdfs. However, it is not a big issue.

**Comment by lee-robin** [comment]
SHB_basin
Wairarapa_basin

Cross section locations attached. Agree with Andrew, worth figuring out that functionality if someone has capacity to at some stage.

**Comment by AndrewStolte** [comment]
I think these basins are fine. Is the slicing script to generate the PDFS pulling directly from the NZVM in its "current" state? I notice that other basins are showing up in the cross sections. This is fine, but somewhat distracts from the examination of the individual basin at hand.

Anyways, I am happy to approve this change or whatever needs to be done.

**Comment by lee-robin** [comment]
Looked over things again as Slice 1 from Wairarapa was bothering me when I didn't see the offshore smoothing. Found we need to change the smoothing file extension from a .dat to .txt:

 Data/Boundaries/Smoothing/Wairarapa_v21p12.dat 
to
 Data/Boundaries/Smoothing/Wairarapa_v21p12.txt

If we can do this and regenerate the Wairarapa plots then we should be good. If the cross sections can be shifted so we get more cross sections in the southern/offshore area that would be nice, although not necessary.

**Comment by jasonmotha** [comment]
Agreed that the outline would be nice on the image. Probably worth asking Ethan how he did it.
[CrossSection_vs_slices.pdf](https://github.com/ucgmsim/Velocity-Model/files/7682092/CrossSection_vs_slices.pdf)
[SliceParametersAuto.txt](https://github.com/ucgmsim/Velocity-Model/files/7682093/SliceParametersAuto.txt)
[VelModDomainBox.pdf](https://github.com/ucgmsim/Velocity-Model/files/7682094/VelModDomainBox.pdf)

**Review by lee-robin — APPROVED** [review]

**Pull request merged**
