### PR TITLE
Removed redundant lines

### PR DESCRIPTION
**Pull request by sungeunbae**
Came across this one while reading the code 

From the readme, it reads,

> v1.64 Same as v1.63 with updated 1D velocity model
> 1D model version (Cant1D_v2.fd_modfile)

But there are actually 2 additional differences between two versions.

1. BPVSubMod_v3 -> BPVSubMod_v4 (see load_Banks_Peninsula_Volcanics_v19p1())
2. v1.64 has an additional surface and veloSubMod

If 2 is not intended, the lines I removed in this PR must be brought back, and lines assuming nSurf=3 and nVeloSubMod=2 should be removed instead.

### CODE REVIEW

**Comment by jasonmotha** [comment]
@lee-robin Is this worth pushing through? Or just leave as is. I don't think 1.64 will branch off any more versions of the VM code so even though it's potentially ugly - it doesn't hurt to leave it functioning as it was?

**Comment by jasonmotha** [comment]
@sungeunbae Now that we've proposed a bigger change. Are you able to generate a VM for the existing code and the proposed code and show that they have the same values?

**Comment by lee-robin** [comment]
Sorry for the delay in getting to this, I looked at it earlier but forgot to comment. All of these changes make sense.

I think if we can do a few checks to make sure nothing changes then I'm happy for this to go through. This would need comparison of VMs (probably standard one we use for Darfield EQ in Canterbury as most changes are for the Canterbury basin part of the code) of the following versions using the code before and after your suggested changes:
1. v1.64
2. v1.67
3. 2.07 (just to check latest doesn't break?)
Any thoughts on this course of action?

**Comment by sungeunbae** [comment]
> Sorry for the delay in getting to this, I looked at it earlier but forgot to comment. All of these changes make sense.
> 
> I think if we can do a few checks to make sure nothing changes then I'm happy for this to go through. This would need comparison of VMs (probably standard one we use for Darfield EQ in Canterbury as most changes are for the Canterbury basin part of the code) of the following versions using the code before and after your suggested changes:
> 
> 1. v1.64
> 2. v1.67
> 3. 2.07 (just to check latest doesn't break?)
>    Any thoughts on this course of action?

Sounds good. Do you have Darfield vm_params?

**Comment by sungeunbae** [comment]
VM generated with binaries Before/After the change. 
Ver 2.07 (the latest 2.07 was added to the branch)
-----
(venv) sungbae@~/Velocity-Model/Full_Velo_Mod.cleanup/Velocity_Model$ for x in *; do md5sum $x; done
fdd85d9c57602c0bcd7a9691ddc32dbf  in_basin_mask.b
a207352c8356bfe362dea02344ffa3c7  rho3dfile.d
fabdde79a05a11d8543985e93ebeb997  vp3dfile.p
2d5d99895462a34225785b4b1386ae68  vs3dfile.s

(venv) sungbae@~/Velocity-Model/Full_Velo_Mod.original/Velocity_Model$ for x in *; do md5sum $x; done
fdd85d9c57602c0bcd7a9691ddc32dbf  in_basin_mask.b
a207352c8356bfe362dea02344ffa3c7  rho3dfile.d
fabdde79a05a11d8543985e93ebeb997  vp3dfile.p
2d5d99895462a34225785b4b1386ae68  vs3dfile.s

**Comment by lee-robin** [comment]
> VM generated with binaries Before/After the change. Ver 2.07 (the latest 2.07 was added to the branch) is identical.
> 
> (venv) sungbae@~/Velocity-Model/Full_Velo_Mod.cleanup/Velocity_Model$ for x in *; do md5sum $x; done fdd85d9c57602c0bcd7a9691ddc32dbf in_basin_mask.b a207352c8356bfe362dea02344ffa3c7 rho3dfile.d fabdde79a05a11d8543985e93ebeb997 vp3dfile.p 2d5d99895462a34225785b4b1386ae68 vs3dfile.s
> 
> (venv) sungbae@~/Velocity-Model/Full_Velo_Mod.original/Velocity_Model$ for x in *; do md5sum $x; done fdd85d9c57602c0bcd7a9691ddc32dbf in_basin_mask.b a207352c8356bfe362dea02344ffa3c7 rho3dfile.d fabdde79a05a11d8543985e93ebeb997 vp3dfile.p 2d5d99895462a34225785b4b1386ae68 vs3dfile.s

Great. If we can also do the same comparison for v1.64 and v1.67 (the versions directly influenced by the line changes) then we're good to push this through.

**Comment by sungeunbae** [comment]
1.67 identical

------
(venv) sungbae@~/Velocity-Model/1.67$ cd Full_Velo_Mod.original/Velocity_Model
(venv) sungbae@~/Velocity-Model/1.67/Full_Velo_Mod.original/Velocity_Model$ for x in *; do md5sum $x; done
1591efc54f3cfdc9caa9c7b2e2d00522  in_basin_mask.b
87a311f4756407811bdc0d0384fee749  rho3dfile.d
d4389e073a518e06d0633a136217f459  vp3dfile.p
f7b4beaa517b8deca1c41ac2bc98b411  vs3dfile.s
(venv) sungbae@~/Velocity-Model/1.67/Full_Velo_Mod.original/Velocity_Model$ cd -
/Users/sungbae/Velocity-Model/1.67
(venv) sungbae@~/Velocity-Model/1.67$ cd Full_Velo_Mod.cleanup/Velocity_Model
(venv) sungbae@~/Velocity-Model/1.67/Full_Velo_Mod.cleanup/Velocity_Model$ for x in *; do md5sum $x; done
1591efc54f3cfdc9caa9c7b2e2d00522  in_basin_mask.b
87a311f4756407811bdc0d0384fee749  rho3dfile.d
d4389e073a518e06d0633a136217f459  vp3dfile.p
f7b4beaa517b8deca1c41ac2bc98b411  vs3dfile.s

**Comment by sungeunbae** [comment]
1.64 identical
-------

(venv) sungbae@~/Velocity-Model/1.64/Full_Velo_Mod.original/Velocity_Model$ for x in *; do md5sum $x; done
1591efc54f3cfdc9caa9c7b2e2d00522  in_basin_mask.b
3c4f8f889481eba9cee5eb271f1cdb2e  rho3dfile.d
d1e91e4694d349395d3f3591917fb5e7  vp3dfile.p
03a5d5682813ce3643ceb27881b1dcde  vs3dfile.s


(venv) sungbae@~/Velocity-Model/1.64/Full_Velo_Mod.cleanup/Velocity_Model$ for x in *; do md5sum $x; done
1591efc54f3cfdc9caa9c7b2e2d00522  in_basin_mask.b
3c4f8f889481eba9cee5eb271f1cdb2e  rho3dfile.d
d1e91e4694d349395d3f3591917fb5e7  vp3dfile.p
03a5d5682813ce3643ceb27881b1dcde  vs3dfile.s

**Comment by sungeunbae** [comment]
@lee-robin @jasonmotha @jpa198  Confirmed this change produces exactly same Darfield VM for v1.64, v1.67 and v2.07 before and after.

**Review by lee-robin — APPROVED** [review]

**Review by jpa198 — APPROVED** [review]

**Review by jasonmotha — APPROVED** [review]

**Pull request merged**
