### PR TITLE
Chow ni tomo files

### PR DESCRIPTION
**Pull request by sungeunbae**
This is the Chow NI tomography only PR that @jasonmotha requested as a separate one from https://github.com/ucgmsim/Velocity-Model/pull/34

### CODE REVIEW

**Comment by jasonmotha** [comment]
image

This PR still has changes to the VM code. I'm looking for a PR with just the tomo files (and no code changes) so we can actually review the code changes. 

Github gives us this error since the new tomo files are that big.
image

Sorry for not explaining the motivation of what I was looking for before.

**Comment by sungeunbae** [comment]
> image
> 
> This PR still has changes to the VM code. I'm looking for a PR with just the tomo files (and no code changes) so we can actually review the code changes.
> 
> Github gives us this error since the new tomo files are that big. image
> 
> Sorry for not explaining the motivation of what I was looking for before.

Yeah, I understand your motivation, but failed at execution. Will try again

**Comment by sungeunbae** [comment]
Screen Shot 2022-03-08 at 6 14 04 AM
@jasonmotha  For some reason, 2 commits which are already in "development" branch have been included. 
[974fbbf](https://github.com/ucgmsim/Velocity-Model/pull/35/commits/974fbbfa3c15dd56eb944f95dc3d5f9b2c77c5e6)
[c580cfa](https://github.com/ucgmsim/Velocity-Model/pull/35/commits/c580cfa408cf131a467f154c3f5f402ac12464bd)

If you merge this PR into the development branch, the other PR will become lighter for you to view more easily.

**Comment by jasonmotha** [comment]
The screenshot above was specifically from the large commit - aka not just the tomo files.

The other two commits (already in the dev branch) are okay. I can't see what other code has been changed / added in that commit.

you might have to reset the head back to "development" and commit only the tomo files again.

> @jasonmotha For some reason, 2 commits which are already in "development" branch have been included ( hash values are different)
> 
> [974fbbf](https://github.com/ucgmsim/Velocity-Model/pull/35/commits/974fbbfa3c15dd56eb944f95dc3d5f9b2c77c5e6) [91bdeee](https://github.com/ucgmsim/Velocity-Model/pull/35/commits/91bdeee8db7710cfb1a45580c2a31493764ead6a)
> 
> Screenshot from development branch shows: Screen Shot 2022-03-08 at 6 14 04 AM You can consider this as the tomo data only PR. If you merge this PR into the development branch, the other PR will become lighter for you to view more easily.

**Comment by sungeunbae** [comment]
Replaced by https://github.com/ucgmsim/Velocity-Model/pull/39

**Pull request closed without merging**
